---
title: "R Notebook"
output: html_notebook
---



Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 

```{r packages, include=FALSE}
library(haven)
library(foreign)
library(car)
library(ggplot2)
library(dplyr)
library(multilevel)

```


Loading DataALLBUS und Makrodaten

```{r include=FALSE}
getwd()
allbus <- read_sav("./data/ALLBUS2018/ZA5270_v2-0-0.sav")

makrodata <- read.csv("./data/BB_BE_Kommulativ_1956bis2015.csv", sep = ";" )


```


Pre Merge Datenaufbereitung



```{r}

#Land Variable muss umcodiert werden zu char und Vektor 
allbus$land<- as.character(allbus$land)

allbus$land_fac <- car::recode(allbus$land,
                      "10 = 'Schleswig-Holstein';
                      20 = 'Hamburg';
                      30 = 'Niedersachsen';
                      40 ='Bremen';
                      50 = 'Nordrhein-Westfalen';
                      60 = 'Hessen';
                      70 = 'Rheinland-Pfalz';
                      80 = 'Baden-Württemberg';
                      90 = 'Bayern';
                      100 = 'Saarland';
                      c(111,112) = 'Berlin';
                      120 = 'Brandenburg';
                      130 = 'Mecklenburg-Vorpommern';
                      140 = 'Sachsen';
                      150 = 'Sachsen-Anhalt';
                      160 = 'Thüringen'",
                      as.factor = TRUE)

# MERGING Datensätze zusammenführen anhand der Bundesländer

newdata <- merge(allbus, makrodata, by="land_fac", na.rm = "TRUE")


#Jede Person aus einem Bundesland hat jetzt die Werte des Bundeslandes auf der entsprechenden Makrovariable
newdata$Verfahren_gesamt
```

